// Package dbcache provides a generic caching layer for database queries in Go.
//
// Design Goals:
// 1. Provide a transparent caching layer for frequently accessed database data
// 2. Support SQL templates with parameterized queries
// 3. Generic type safety for any data type
// 4. Automatic cache population on cache misses
// 5. Configurable expiration and cleanup intervals
//
// Core Features:
// - SQL Templating: Parameterized query support with $1, $2 placeholders
// - Automatic Caching: Transparent cache population when data is not in cache
// - Type Safety: Generics support for any data type
// - Cache Control: Configurable expiration and cleanup intervals
// - Custom Loaders: Optional custom loader functions for complex data loading
// - Memory Efficiency: Uses go-cache for efficient in-memory storage
//
// Use Cases:
// - Frequently accessed database records (users, products, settings)
// - Expensive query result caching
// - Rate-limited API response caching
// - Configuration storage optimization
// - Static reference data caching
//
// Basic Usage:
//
//	import (
//	    "database/sql"
//	    "time"
//	    "github.com/kaichao/gopkg/dbcache"
//	)
//
//	func main() {
//	    db, err := sql.Open("postgres", "postgres://user:password@localhost/dbname")
//	    if err != nil {
//	        panic(err)
//	    }
//	    defer db.Close()
//
//	    // Initialize cache for user emails
//	    emailCache := dbcache.New[string](
//	        db,
//	        "SELECT email FROM users WHERE id = $1",
//	        5*time.Minute,  // Default cache expiration
//	        10*time.Minute, // Cleanup interval
//	        nil,            // Use default SQL loader
//	    )
//
//	    // Get user email - first call queries database, second uses cache
//	    email, err := emailCache.Get(123)
//	    if err != nil {
//	        panic(err)
//	    }
//	    fmt.Println("User email:", email)
//	}
//
// Advanced Usage with Custom Loader:
//
//	import (
//	    "fmt"
//	    "time"
//	    "github.com/kaichao/gopkg/dbcache"
//	)
//
//	func main() {
//	    // Custom hash generator (no database needed)
//	    loader := func(params ...any) (string, error) {
//	        id := params[0].(int)
//	        return fmt.Sprintf("hash-%d", id), nil
//	    }
//
//	    // Create cache with custom loader
//	    hashCache := dbcache.New[string](
//	        nil, // No database connection needed
//	        "",  // No SQL template needed
//	        time.Hour, 2*time.Hour,
//	        loader,
//	    )
//
//	    // Get cached hash
//	    hash, err := hashCache.Get(42)
//	    if err != nil {
//	        panic(err)
//	    }
//	    fmt.Println("Generated hash:", hash)
//	}
//
// API Reference:
//
//	// New creates a new database cache instance
//	func New[T any](
//	    db *sql.DB,
//	    sqlTemplate string,
//	    defaultExp, cleanupInterval time.Duration,
//	    loader func(...any) (T, error),
//	) *DBCache[T]
//
//	// Get retrieves value from cache or loads it using the SQL template/custom loader
//	func (c *DBCache[T]) Get(params ...any) (T, error)
//
// Error Handling:
// All errors are returned as-is from database operations or custom loader functions.
// No special error wrapping is applied, allowing callers to handle errors directly.
//
// Performance Considerations:
// - Cache keys are generated by formatting parameters with fmt.Sprintf("%v", params)
// - Consider using more efficient key generation for high-throughput applications
// - Default expiration and cleanup intervals should be tuned based on data freshness requirements
// - Memory usage scales with cached data and expiration settings
//
// Dependencies:
// - github.com/patrickmn/go-cache: In-memory cache implementation
// - Go 1.18 or higher (generic type support required)
//
// License: MIT
package dbcache
